# Generated by Django 5.1.3 on 2024-12-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nit',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nit_cedula',
            field=models.CharField(default='890927624', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('31', 'NIT'), ('13', 'Cédula'), ('22', 'Cédula de Extranjería'), ('43', 'Código Extranjero'), ('12', 'Tarjeta de Identidad'), ('11', 'Registro Civil'), ('41', 'Pasaporte')], default='cc', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='entidad_bancaria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('Ahorros', 'Ahorros'), ('Corriente', 'Corriente')], max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table=None,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='responsabilidades',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='gestion.responsabilidad'),
        ),
    ]
